import nodemailer from 'nodemailer';

const clean=value=>String(value??'').replace(/[\r\n\0]/g,' ').trim();
const html=value=>clean(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

export function smtpConfigured(env=process.env){const authReady=(!env.SMTP_USER&&!env.SMTP_PASS)||(Boolean(env.SMTP_USER)&&Boolean(env.SMTP_PASS));return Boolean(env.SMTP_HOST&&env.SMTP_FROM&&env.SMTP_TO&&authReady)}

export function shoppingEmail(items,week=''){const safe=items.slice(0,500).map(item=>({aisle:clean(item.aisle)||'Other',name:clean(item.name).slice(0,160),quantity:clean(item.quantity).slice(0,40),recipes:(Array.isArray(item.recipes)?item.recipes:[]).map(clean).filter(Boolean).slice(0,20)})).filter(item=>item.name),groups=Map.groupBy(safe,item=>item.aisle),title=`Savorly shopping list${week?` — ${clean(week).slice(0,80)}`:''}`,text=[title,'',...[...groups].flatMap(([aisle,list])=>[aisle,...list.map(item=>`- ${item.quantity} ${item.name}${item.recipes.length?` (${item.recipes.join(', ')})`:''}`),''])].join('\n'),body=[`<h1 style="color:#315441">${html(title)}</h1>`,...[...groups].map(([aisle,list])=>`<h2>${html(aisle)}</h2><ul>${list.map(item=>`<li><strong>${html(item.quantity)}</strong> ${html(item.name)}${item.recipes.length?`<br><small>${html(item.recipes.join(', '))}</small>`:''}</li>`).join('')}</ul>`),'<p style="color:#708078">Sent from your self-hosted Savorly planner.</p>'].join('');return{subject:title,text,html:body,itemCount:safe.length}}

export async function sendShoppingEmail(items,week='',env=process.env){if(!smtpConfigured(env))throw new Error('SMTP is not configured');const port=Number(env.SMTP_PORT)||587,secure=String(env.SMTP_SECURE||'').toLowerCase()==='true'||port===465,auth=env.SMTP_USER?{user:env.SMTP_USER,pass:env.SMTP_PASS}:undefined,transport=nodemailer.createTransport({host:env.SMTP_HOST,port,secure,auth,requireTLS:String(env.SMTP_REQUIRE_TLS||'').toLowerCase()==='true',connectionTimeout:10000,greetingTimeout:10000,socketTimeout:15000,disableFileAccess:true,disableUrlAccess:true,pool:false});const content=shoppingEmail(items,week);await transport.sendMail({from:env.SMTP_FROM,to:env.SMTP_TO,subject:content.subject,text:content.text,html:content.html});return{itemCount:content.itemCount}}
