import http from 'node:http';
import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const base=path.dirname(fileURLToPath(import.meta.url)),root=path.join(base,'public'),dataDir=process.env.DATA_DIR||path.join(base,'data'),dataFile=path.join(dataDir,'state.json');
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};
const recipes=[
 {id:'veggie-bowl',title:'Roasted veggie bowl',time:30,difficulty:'Easy',calories:520,protein:24,servings:2,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85',ingredients:[['Sweet potato',2,'whole','Produce'],['Broccoli',1,'head','Produce'],['Chickpeas',1,'can','Pantry'],['Quinoa',1,'cup','Pantry'],['Tahini',3,'tbsp','Condiments'],['Lemon',1,'whole','Produce']]},
 {id:'herb-chicken',title:'Herb chicken & potatoes',time:40,difficulty:'Easy',calories:640,protein:52,servings:2,image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=85',ingredients:[['Chicken breast',1,'lb','Meat'],['Baby potatoes',1,'lb','Produce'],['Green beans',8,'oz','Produce'],['Olive oil',2,'tbsp','Pantry'],['Rosemary',2,'sprigs','Produce'],['Garlic',3,'cloves','Produce']]},
 {id:'quinoa',title:'Green goddess quinoa',time:25,difficulty:'Easy',calories:480,protein:22,servings:2,image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',ingredients:[['Quinoa',1,'cup','Pantry'],['Avocado',1,'whole','Produce'],['Cucumber',1,'whole','Produce'],['Spinach',3,'cups','Produce'],['Feta',4,'oz','Dairy'],['Lemon',1,'whole','Produce']]},
 {id:'salmon',title:'Miso glazed salmon',time:35,difficulty:'Medium',calories:590,protein:46,servings:2,image:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=85',ingredients:[['Salmon fillets',2,'whole','Seafood'],['White miso',2,'tbsp','Condiments'],['Rice',1,'cup','Pantry'],['Bok choy',2,'heads','Produce'],['Soy sauce',1,'tbsp','Condiments'],['Scallions',3,'whole','Produce']]},
 {id:'oats',title:'Berry almond overnight oats',time:10,difficulty:'Easy',calories:410,protein:25,servings:2,image:'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=900&q=85',ingredients:[['Rolled oats',1,'cup','Pantry'],['Greek yogurt',1,'cup','Dairy'],['Almond milk',1,'cup','Dairy'],['Mixed berries',1,'cup','Produce'],['Chia seeds',2,'tbsp','Pantry'],['Almond butter',2,'tbsp','Condiments']]},
 {id:'turkey-wrap',title:'Crunchy turkey avocado wraps',time:15,difficulty:'Easy',calories:455,protein:38,servings:2,image:'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=85',ingredients:[['Whole wheat tortillas',2,'whole','Bakery'],['Turkey breast',8,'oz','Deli'],['Avocado',1,'whole','Produce'],['Romaine',2,'cups','Produce'],['Tomato',1,'whole','Produce'],['Greek yogurt',3,'tbsp','Dairy']]}
].map(r=>({...r,ingredients:r.ingredients.map(([name,quantity,unit,aisle])=>({name,quantity,unit,aisle}))}));
const defaults={goals:{calories:2100,protein:150},plan:[{id:'sample-1',recipeId:'veggie-bowl',day:'Monday',slot:'Lunch',servings:2},{id:'sample-2',recipeId:'herb-chicken',day:'Monday',slot:'Dinner',servings:2},{id:'sample-3',recipeId:'quinoa',day:'Tuesday',slot:'Lunch',servings:2}],checked:[]};
async function getState(){try{return JSON.parse(await readFile(dataFile,'utf8'))}catch{await mkdir(dataDir,{recursive:true});await writeFile(dataFile,JSON.stringify(defaults,null,2));return structuredClone(defaults)}}
function valid(b){return b&&Number.isFinite(b.goals?.calories)&&Number.isFinite(b.goals?.protein)&&Array.isArray(b.plan)&&Array.isArray(b.checked)}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>1e6)throw Error()}return JSON.parse(raw)}
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value))}
export const server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/api/state'&&req.method==='GET')return json(res,200,{...await getState(),recipes});if(pathname==='/api/state'&&req.method==='PUT'){try{const next=await body(req);if(!valid(next))return json(res,400,{error:'Invalid planner data'});const safe={goals:next.goals,plan:next.plan.filter(m=>recipes.some(r=>r.id===m.recipeId)),checked:next.checked,updatedAt:new Date().toISOString()};await mkdir(dataDir,{recursive:true});await writeFile(dataFile,JSON.stringify(safe,null,2));return json(res,200,safe)}catch{return json(res,400,{error:'Invalid request'})}}const candidate=path.normalize(path.join(root,pathname==='/'?'index.html':pathname));if(!candidate.startsWith(root))return res.writeHead(403).end('Forbidden');try{if(!(await stat(candidate)).isFile())throw Error();res.writeHead(200,{'Content-Type':types[path.extname(candidate)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(await readFile(candidate))}catch{res.writeHead(404).end('Not found')}});
if(process.env.NODE_ENV!=='test')server.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log(`Local: http://localhost:${process.env.PORT||3000}`));
